def calculate(a, b, operacja):
    if operacja == "+":
        return a + b
    if operacja == "-":
        return a - b
    if operacja == "/":
        return a / b
    if operacja == "%":
        return a % b
    if operacja == "**":
        return a ** b
